version: '3'
services:
  sharelatex:
    image: sharelatex/sharelatex
    restart: on-failure
    volumes:
      - ./data:/var/lib/sharelatex
    ports:
      - 8080:80
    environment:
      - SHARELATEX_MONGO_URL=mongodb://mongo:27017/sharelatex?replicaSet=rs
      - SHARELATEX_REDIS_HOST=redis
      - SHARELATEX_SITE_URL=http://localhost:8080
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    command: mongod --replSet rs
    restart: on-failure
    volumes:
      - ./data-mongo:/data/db
  redis:
    image: redis
    restart: on-failure
    volumes:
      - ./data-redis:/data

     -  SHARELATEX_NAVIGATION_METHOD: "url"
     - SHARELATEX_APP_NAME: "Overleaf"
     - SHARELATEX_ENABLE_PDFLATEX: "true"
     - SHARELATEX_ALLOW_COMPILE_TIMEOUT: "true"
     - SHARELATEX_ALLOW_USER_REGISTRATION: "true"
     - SHARELATEX_ALLOW_ANONYMOUS_READ_AND_WRITE: "false"
     - SHARELATEX_SESSION_SECRET: "Pw32niFGT&72n9HDJSLAUBD"
     - SHARELATEX_ENABLE_PDF_UPLOADS: "true"
